### ISSUE TITLE
Error 403 - Forbidden

### ISSUE THREAD

**Issue by stefankuehnel** [Athlon1600/youtube-downloader#23] opened 2018-09-08 10:28 UTC
The Demo API and the code are working but when I try to access the video ressources given, googlevideo.com responds with either a 403 Forbidden Error or a blank page.

I tried to access the ressource with Chrome, Firefox and a different IP with the Tor Browser. 

All test weren't successful. Maybe YouTube changed something in their code. When I access the Demo Stream Version it redirects me to redirector.googlevideo.com instead of https://---.googlevideo.com/videoplayback?...

**Comment by Ahmed18** [comment] 2018-09-10 14:29
i have the same issue

**Comment by harisnaeemofficial** [comment] 2018-09-12 12:47
Same Issue please resolve it . the same issue was facing youtube-dl but in the latest update the issue is resolved . there is new extraction method for youtube video signature which is causing the problem .

**Comment by scrapewww** [comment] 2018-11-29 18:44
also getting 403 error when actually trying to download provided urls..

**Comment by stuthemoo** [comment] 2018-12-05 02:36
I'm also seeing the 403 error for all video URLs.

**Comment by madcode-git** [comment] 2018-12-15 08:07
Use this one https://github.com/madcode-git/YouTube-Downloader

**Comment by Athlon1600** [comment] 2018-12-27 02:31
Fix has been made and links in the demo section are now working:  
https://github.com/Athlon1600/youtube-downloader/commit/a2c1e1c6165d85573db701705fe490ffe79852f6

**Closed by Athlon1600** 2018-12-27 02:31 UTC
