### ISSUE TITLE
Some videos do not return links

### ISSUE THREAD

**Issue by AgentSmith0** [Athlon1600/youtube-downloader#113] opened 2021-06-04 15:07 UTC
Try here: https://youtube-downloader-v3.herokuapp.com/
With this video: https://www.youtube.com/watch?v=QonEs-Teci4
The most other videos are working, only older ones are not always working.
This issue is probably a duplicate of #109.

**Comment by AgentSmith0** [comment] 2021-06-04 15:10
Closed, because duplicate of #109

**Comment by Athlon1600** [comment] 2021-06-08 21:20
duplicate of #109

**Closed by Athlon1600** 2021-06-08 21:20 UTC
