### ISSUE TITLE
getdownloadlinks method issue

### ISSUE THREAD

**Issue by sareban101** [Athlon1600/youtube-downloader#105] opened 2021-04-08 04:16 UTC
It unable to find links for videos released more than two years ago

please fix it

thank you for your lib 🌺

**Comment by AgentSmith0** [comment] 2021-06-06 07:10
Probably a duplicate of #109. Please leave a comment there.

**Comment by Athlon1600** [comment] 2021-06-08 21:21
Need to know which videos specifically can't be downloaded, but since this issue is already months old, it has probably since been fixed already. Try using latest release.

**Closed by Athlon1600** 2021-06-08 21:21 UTC
