### ISSUE TITLE
Only one video format has audio

### ISSUE THREAD

**Issue by jahanzaibniazi** [Athlon1600/youtube-downloader#65] opened 2020-07-19 06:59 UTC
I have tried to download it fetches many video formats but only one mp4 format has the audio, other formats does not have audio with them. How can i resolve this issue???

**Comment by Athlon1600** [comment] 2020-07-19 16:42
That's expected behavior, because youtube itself splits its streams into separate containers for audio and video, and then plays them both at the same time. Eventually I plan on adding an option that lets you download both streams separately and then merge them together just like python's youtube-dl does.
This is a duplicate of:  
https://github.com/Athlon1600/youtube-downloader/issues/44#issuecomment-606948010

**Closed by Athlon1600** 2020-07-19 16:42 UTC

**Comment by jahanzaibniazi** [comment] 2020-07-19 18:53
Thanks sir for your kind response.!
